use_frameworks!

platform :ios, '10.0'

target 'InfinitScrollView_Example' do
  pod 'InfinitScrollView', :path => '../'

  target 'InfinitScrollView_Tests' do
    inherit! :search_paths

    
  end
end
